//By Ajlal Paracha in Mr. Martins Gr.11 NightSchool CS Class on March 6th, 2021
//This is the magical math methods program - Enjoy!
public class magical_math_frm extends javax.swing.JFrame {

    /**
     * Creates new form magical_math_frm
     */
    public magical_math_frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        input_txt_greater1 = new javax.swing.JTextField();
        input_txt_greater2 = new javax.swing.JTextField();
        btn_greater = new javax.swing.JButton();
        lbl_anwser_greater = new javax.swing.JLabel();
        input_txt_lesser1 = new javax.swing.JTextField();
        input_txt_lesser2 = new javax.swing.JTextField();
        btn_lesser = new javax.swing.JButton();
        lbl_anwser_lesser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_txt_base = new javax.swing.JTextField();
        input_txt_exp = new javax.swing.JTextField();
        btn_power = new javax.swing.JButton();
        lbl_anwser_power = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_txt_right1 = new javax.swing.JTextField();
        input_txt_right2 = new javax.swing.JTextField();
        btn_right = new javax.swing.JButton();
        lbl_anwser_right = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input_txt_down = new javax.swing.JTextField();
        btn_down = new javax.swing.JButton();
        lbl_anwser_down = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input_txt_up = new javax.swing.JTextField();
        btn_up = new javax.swing.JButton();
        lbl_anwser_up = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        input_txt_root = new javax.swing.JTextField();
        btn_root = new javax.swing.JButton();
        lbl_anwser_root = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        input_txt_rad = new javax.swing.JTextField();
        btn_rad = new javax.swing.JButton();
        lbl_anwser_rad = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 200));
        label_title.setText("Magical Math Methods");

        jLabel1.setText("Enter two numbers and button and the program will display the greater one.");

        btn_greater.setText("Greatest");
        btn_greater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_greaterActionPerformed(evt);
            }
        });

        lbl_anwser_greater.setText("__");

        btn_lesser.setText("Least");
        btn_lesser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lesserActionPerformed(evt);
            }
        });

        lbl_anwser_lesser.setText("__");

        jLabel2.setText("Enter two numbers and button and the program will display the lesser one.");

        btn_power.setText("Power");
        btn_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_powerActionPerformed(evt);
            }
        });

        lbl_anwser_power.setText("__");

        jLabel3.setText("Enter two numbers and the button and the program will raise the 1st to the second.");

        btn_right.setText("Hypotenuse");
        btn_right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rightActionPerformed(evt);
            }
        });

        lbl_anwser_right.setText("__");

        jLabel4.setText("Enter two side lengths of a right triangle and the button and the program will compute the hypotenuse");

        btn_down.setText("Round Down");
        btn_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_downActionPerformed(evt);
            }
        });

        lbl_anwser_down.setText("__");

        jLabel5.setText("Enter a decimal value and the button and the program will round down to nearest integer.");

        btn_up.setText("Round Up");
        btn_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upActionPerformed(evt);
            }
        });

        lbl_anwser_up.setText("__");

        jLabel6.setText("Enter a decimal value and the button and the program will round up to nearest integer.");

        btn_root.setText("Square Root");
        btn_root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rootActionPerformed(evt);
            }
        });

        lbl_anwser_root.setText("__");

        jLabel7.setText("Enter an integer and the button and the program will compute the square root");

        btn_rad.setText("Radians");
        btn_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_radActionPerformed(evt);
            }
        });

        lbl_anwser_rad.setText("__");

        jLabel8.setText("Enter an angle in degrees and the button and the program will output it in radians.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(input_txt_rad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_rad)
                        .addGap(68, 68, 68)
                        .addComponent(lbl_anwser_rad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(input_txt_root, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_root)
                        .addGap(68, 68, 68)
                        .addComponent(lbl_anwser_root))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(input_txt_up, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_up)
                        .addGap(68, 68, 68)
                        .addComponent(lbl_anwser_up))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(input_txt_down, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_down)
                        .addGap(68, 68, 68)
                        .addComponent(lbl_anwser_down))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(input_txt_right1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_txt_right2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_right)
                        .addGap(51, 51, 51)
                        .addComponent(lbl_anwser_right))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(input_txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_txt_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_power)
                        .addGap(79, 79, 79)
                        .addComponent(lbl_anwser_power))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(input_txt_lesser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_txt_lesser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lesser)
                        .addGap(87, 87, 87)
                        .addComponent(lbl_anwser_lesser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(label_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(input_txt_greater1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_txt_greater2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_greater)
                        .addGap(68, 68, 68)
                        .addComponent(lbl_anwser_greater))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label_title)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_txt_greater1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_txt_greater2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_greater))
                    .addComponent(lbl_anwser_greater))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_txt_lesser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_txt_lesser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lesser)
                    .addComponent(lbl_anwser_lesser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_txt_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_power))
                    .addComponent(lbl_anwser_power))
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_txt_right1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_txt_right2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_right))
                    .addComponent(lbl_anwser_right))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_txt_down, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_down))
                    .addComponent(lbl_anwser_down))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_txt_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_up))
                    .addComponent(lbl_anwser_up))
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_txt_root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_root))
                    .addComponent(lbl_anwser_root))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_txt_rad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_rad))
                    .addComponent(lbl_anwser_rad))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_greaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_greaterActionPerformed
        //getting double values from txt input fields
        double greater1 = Double.parseDouble(input_txt_greater1.getText());
        double greater2 = Double.parseDouble(input_txt_greater2.getText());
        //checking which is greater and outputting that one. If same, then output same. 
        if (greater1 > greater2) {
            lbl_anwser_greater.setText(String.valueOf(greater1));
        }
        else if (greater1 < greater2) {
            lbl_anwser_greater.setText(String.valueOf(greater2));
        }
        else {
            lbl_anwser_greater.setText(String.valueOf("Same."));
        }
        
    }//GEN-LAST:event_btn_greaterActionPerformed

    private void btn_lesserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lesserActionPerformed
        //getting double values from txt input fields
        double lesser1 = Double.parseDouble(input_txt_lesser1.getText());
        double lesser2 = Double.parseDouble(input_txt_lesser2.getText());
        //checking which is lesser and outputting that one. If same, then output same. 
        if (lesser1 > lesser2) {
            lbl_anwser_lesser.setText(String.valueOf(lesser2));
        }
        else if (lesser1 < lesser2) {
            lbl_anwser_lesser.setText(String.valueOf(lesser1));
        }
        else {
            lbl_anwser_lesser.setText(String.valueOf("Same."));
        }
    }//GEN-LAST:event_btn_lesserActionPerformed

    private void btn_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_powerActionPerformed
        //getting double values from txt input fields
        double base  = Double.parseDouble(input_txt_base.getText());
        double exp1 = Double.parseDouble(input_txt_exp.getText());
        //computing anwser with math.pow and outputting
        lbl_anwser_power.setText(String.valueOf(Math.pow(base,exp1)));
        
    }//GEN-LAST:event_btn_powerActionPerformed

    private void btn_rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rightActionPerformed
        //getting double values from txt input fields
        double side1 = Double.parseDouble(input_txt_right1.getText());
        double side2 = Double.parseDouble(input_txt_right2.getText());
        
        //computing anwser with formula sqrt(a^2 + b^2) and outputting
        lbl_anwser_right.setText(String.valueOf(Math.pow((side1 * side1 + side2 * side2),0.5)));
    }//GEN-LAST:event_btn_rightActionPerformed

    private void btn_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_downActionPerformed

        //getting double values from txt input fields
        double down = Double.parseDouble(input_txt_down.getText());
        //computing anwser with math.floor and converting to int and outputting
        lbl_anwser_down.setText(String.valueOf((int)Math.floor(down)));
    }//GEN-LAST:event_btn_downActionPerformed

    private void btn_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upActionPerformed
        //getting double values from txt input fields
        double up = Double.parseDouble(input_txt_up.getText());
        //computing anwser with math.ceil and converting to int and outputting
        lbl_anwser_up.setText(String.valueOf((int)Math.ceil(up)));
    }//GEN-LAST:event_btn_upActionPerformed

    private void btn_rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rootActionPerformed
        //getting double values from txt input fields
        double root = Double.parseDouble(input_txt_root.getText());
        //computing anwser with math.pow and  outputting
        lbl_anwser_root.setText(String.valueOf(Math.pow(root,0.5)));
    }//GEN-LAST:event_btn_rootActionPerformed

    private void btn_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_radActionPerformed
        //getting double values from txt input fields
        double rad = Double.parseDouble(input_txt_rad.getText());
        //computing anwser with formula pi/180
        double anwser = (rad * (Math.PI/180.0))/Math.PI;
        lbl_anwser_rad.setText(String.valueOf(anwser + " radians"));
    }//GEN-LAST:event_btn_radActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(magical_math_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(magical_math_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(magical_math_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(magical_math_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new magical_math_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_down;
    private javax.swing.JButton btn_greater;
    private javax.swing.JButton btn_lesser;
    private javax.swing.JButton btn_power;
    private javax.swing.JButton btn_rad;
    private javax.swing.JButton btn_right;
    private javax.swing.JButton btn_root;
    private javax.swing.JButton btn_up;
    private javax.swing.JTextField input_txt_base;
    private javax.swing.JTextField input_txt_down;
    private javax.swing.JTextField input_txt_exp;
    private javax.swing.JTextField input_txt_greater1;
    private javax.swing.JTextField input_txt_greater2;
    private javax.swing.JTextField input_txt_lesser1;
    private javax.swing.JTextField input_txt_lesser2;
    private javax.swing.JTextField input_txt_rad;
    private javax.swing.JTextField input_txt_right1;
    private javax.swing.JTextField input_txt_right2;
    private javax.swing.JTextField input_txt_root;
    private javax.swing.JTextField input_txt_up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel lbl_anwser_down;
    private javax.swing.JLabel lbl_anwser_greater;
    private javax.swing.JLabel lbl_anwser_lesser;
    private javax.swing.JLabel lbl_anwser_power;
    private javax.swing.JLabel lbl_anwser_rad;
    private javax.swing.JLabel lbl_anwser_right;
    private javax.swing.JLabel lbl_anwser_root;
    private javax.swing.JLabel lbl_anwser_up;
    // End of variables declaration//GEN-END:variables
}
